import { Routes } from '@angular/router';
import { InicioComponent } from './componentes/inicio/inicio.component';
import { AcercaComponent } from './componentes/acerca/acerca.component';
import { BarraLateralComponent } from './componentes/barra-lateral/barra-lateral.component';
import { BlogComponent } from './componentes/blog/blog.component';
import { DashboardComponent } from './componentes/dashboard/dashboard.component';
import { FooterComponent } from './componentes/footer/footer.component';
import { GaleriaComponent } from './componentes/galeria/galeria.component';
import { HeaderComponent } from './componentes/header/header.component';
import { HiComponent } from './componentes/hi/hi.component';
import { LoginComponent } from './componentes/login/login.component';
import { ProductosComponent } from './componentes/productos/productos.component';
import { ComponentesComponent } from './componentes/componentes.component';
import { ContactameComponent } from './componentes/contactame/contactame.component';
import { PeluqueriaComponent } from './componentes/peluqueria/peluqueria.component';
import { ServiciosComponent } from './componentes/servicios/servicios.component';
import { DInicioComponent } from './componentes/d-inicio/d-inicio.component';
import { DPeluqueriaComponent } from './componentes/d-peluqueria/d-peluqueria.component';
import { DServiciosComponent } from './componentes/d-servicios/d-servicios.component';
import { DProductosComponent } from './componentes/d-productos/d-productos.component';
import { DGaleriaComponent } from './componentes/d-galeria/d-galeria.component';
import { DBlogComponent } from './componentes/d-blog/d-blog.component';
import { DAcercaDeMiComponent } from './componentes/d-acerca-de-mi/d-acerca-de-mi.component';
import { DContactameComponent } from './componentes/d-contactame/d-contactame.component';
import { DMetricasComponent } from './componentes/d-metricas/d-metricas.component';
import { DCrearPerfilComponent } from './componentes/d-crear-perfil/d-crear-perfil.component';



export const routes: Routes = [
    { path: 'componentes', component: ComponentesComponent },
    { path: 'inicio', component: InicioComponent },
    { path: 'acerca', component: AcercaComponent },
    { path: 'barra-lateral', component: BarraLateralComponent },
    { path: 'blog', component: BlogComponent },
    { path: 'dashboard', component: DashboardComponent },
    { path: 'footer', component: FooterComponent },
    { path: 'galeria', component: GaleriaComponent },
    { path: 'header', component: HeaderComponent },
    { path: 'hi', component: HiComponent },
    { path: 'login', component: LoginComponent },
    { path: 'productos', component: ProductosComponent },
    { path: 'contactame', component: ContactameComponent },
    { path: 'peluqueria', component: PeluqueriaComponent },
    { path: 'servicios', component: ServiciosComponent },
    { path: 'd-inicio', component: DInicioComponent },
    { path: 'd-peluqueria', component: DPeluqueriaComponent },
    { path: 'd-servicios', component: DServiciosComponent },
    { path: 'd-productos', component: DProductosComponent },
    { path: 'd-galeria', component: DGaleriaComponent },
    { path: 'd-blog', component: DBlogComponent },
    { path: 'd-acerca-de-mi', component: DAcercaDeMiComponent },
    { path: 'd-contactame', component: DContactameComponent },
    { path: 'd-metricas', component: DMetricasComponent },
    { path: 'd-crear-perfil', component: DCrearPerfilComponent },
];